//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgjensioniTuristik.Serveri {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.fidanabdiu.netfirms.com/", ConfigurationName="Serveri.WSSoap")]
    public interface WSSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.fidanabdiu.netfirms.com/Kycu", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Personi))]
        AgjensioniTuristik.Serveri.PerdoruesiAgjensionit Kycu(string pseudonimi, string fjalekalimi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.fidanabdiu.netfirms.com/PerdoruesiAgjensionitShkruaj", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Personi))]
        AgjensioniTuristik.Serveri.PerdoruesiAgjensionit PerdoruesiAgjensionitShkruaj(AgjensioniTuristik.Serveri.PerdoruesiAgjensionit pa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.fidanabdiu.netfirms.com/PerdoruesiAgjensionitNdrysho", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Personi))]
        AgjensioniTuristik.Serveri.PerdoruesiAgjensionit PerdoruesiAgjensionitNdrysho(AgjensioniTuristik.Serveri.PerdoruesiAgjensionit pa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.fidanabdiu.netfirms.com/PerdoruesiAgjensionitLexo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Personi))]
        AgjensioniTuristik.Serveri.PerdoruesiAgjensionit PerdoruesiAgjensionitLexo(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.fidanabdiu.netfirms.com/PerdoruesiAgjensionitFshi", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Personi))]
        void PerdoruesiAgjensionitFshi(AgjensioniTuristik.Serveri.PerdoruesiAgjensionit pa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.fidanabdiu.netfirms.com/PerdoruesiAgjensionitLexoSipasAgjensionit", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Personi))]
        PerdoruesiAgjensionit[] PerdoruesiAgjensionitLexoSipasAgjensionit(int AgjensioniID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.fidanabdiu.netfirms.com/FluturimetLexo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Personi))]
        Fluturimi[] FluturimetLexo(string fjalakyce);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.fidanabdiu.netfirms.com/RezervimiShkruaj", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Personi))]
        AgjensioniTuristik.Serveri.Rezervimi RezervimiShkruaj(AgjensioniTuristik.Serveri.Rezervimi r);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.fidanabdiu.netfirms.com/RezervimiNdrysho", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Personi))]
        AgjensioniTuristik.Serveri.Rezervimi RezervimiNdrysho(AgjensioniTuristik.Serveri.Rezervimi r);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.fidanabdiu.netfirms.com/RezervimiLexo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Personi))]
        AgjensioniTuristik.Serveri.Rezervimi RezervimiLexo(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.fidanabdiu.netfirms.com/RezervimiFshi", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Personi))]
        void RezervimiFshi(AgjensioniTuristik.Serveri.Rezervimi r);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.fidanabdiu.netfirms.com/RezervimetLexoSipasAgjensionit", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Personi))]
        Rezervimi[] RezervimetLexoSipasAgjensionit(int AgjensioniID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.fidanabdiu.netfirms.com/UdhetariShkruaj", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Personi))]
        AgjensioniTuristik.Serveri.Udhetari UdhetariShkruaj(AgjensioniTuristik.Serveri.Udhetari u);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.fidanabdiu.netfirms.com/UdhetariNdrysho", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Personi))]
        AgjensioniTuristik.Serveri.Udhetari UdhetariNdrysho(AgjensioniTuristik.Serveri.Udhetari u);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.fidanabdiu.netfirms.com/UdhetariLexo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Personi))]
        AgjensioniTuristik.Serveri.Udhetari UdhetariLexo(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.fidanabdiu.netfirms.com/UdhetaretLexo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Personi))]
        Udhetari[] UdhetaretLexo(string fjalakyce);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.fidanabdiu.netfirms.com/UlesetLexoSipasAeroplanit", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Personi))]
        Ulesja[] UlesetLexoSipasAeroplanit(int AeroplaniID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.fidanabdiu.netfirms.com/UdhetariFshi", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Personi))]
        void UdhetariFshi(AgjensioniTuristik.Serveri.Udhetari u);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.fidanabdiu.netfirms.com/UlesjaNdrysho", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Personi))]
        AgjensioniTuristik.Serveri.Ulesja UlesjaNdrysho(AgjensioniTuristik.Serveri.Ulesja u);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.fidanabdiu.netfirms.com/UlesetLexoSipasStatusit", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Personi))]
        Ulesja[] UlesetLexoSipasStatusit(int AeroplaniID, AgjensioniTuristik.Serveri.UlesjaEZene UlesjaEZene);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.fidanabdiu.netfirms.com/FluturimetLexoSipasStatusit", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Personi))]
        Fluturimi[] FluturimetLexoSipasStatusit(AgjensioniTuristik.Serveri.FluturimiAnuluar FluturimiAnuluar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.fidanabdiu.netfirms.com/LexoUlesetLira", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Personi))]
        bool LexoUlesetLira(int AeroplaniID, AgjensioniTuristik.Serveri.UlesjaEZene UlesjaEZene);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fidanabdiu.netfirms.com/")]
    public partial class PerdoruesiAgjensionit : Personi {
        
        private Agjensioni agjensioniField;
        
        private string pseudonimiField;
        
        private string fjalekalimiField;
        
        private Privilegji privilegjiField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Agjensioni Agjensioni {
            get {
                return this.agjensioniField;
            }
            set {
                this.agjensioniField = value;
                this.RaisePropertyChanged("Agjensioni");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Pseudonimi {
            get {
                return this.pseudonimiField;
            }
            set {
                this.pseudonimiField = value;
                this.RaisePropertyChanged("Pseudonimi");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Fjalekalimi {
            get {
                return this.fjalekalimiField;
            }
            set {
                this.fjalekalimiField = value;
                this.RaisePropertyChanged("Fjalekalimi");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public Privilegji Privilegji {
            get {
                return this.privilegjiField;
            }
            set {
                this.privilegjiField = value;
                this.RaisePropertyChanged("Privilegji");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fidanabdiu.netfirms.com/")]
    public partial class Agjensioni : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string emriField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Emri {
            get {
                return this.emriField;
            }
            set {
                this.emriField = value;
                this.RaisePropertyChanged("Emri");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fidanabdiu.netfirms.com/")]
    public partial class Ulesja : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private int numriField;
        
        private Aeroplani aeroplaniField;
        
        private UlesjaEZene ulesjaEZeneField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int Numri {
            get {
                return this.numriField;
            }
            set {
                this.numriField = value;
                this.RaisePropertyChanged("Numri");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public Aeroplani Aeroplani {
            get {
                return this.aeroplaniField;
            }
            set {
                this.aeroplaniField = value;
                this.RaisePropertyChanged("Aeroplani");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public UlesjaEZene UlesjaEZene {
            get {
                return this.ulesjaEZeneField;
            }
            set {
                this.ulesjaEZeneField = value;
                this.RaisePropertyChanged("UlesjaEZene");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fidanabdiu.netfirms.com/")]
    public partial class Aeroplani : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private LinjaAjrore linjaAjroreField;
        
        private TipiAeroplanit tipiAeroplanitField;
        
        private MarkaAeroplanit markaAeroplanitField;
        
        private int numriUleseveField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public LinjaAjrore LinjaAjrore {
            get {
                return this.linjaAjroreField;
            }
            set {
                this.linjaAjroreField = value;
                this.RaisePropertyChanged("LinjaAjrore");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public TipiAeroplanit TipiAeroplanit {
            get {
                return this.tipiAeroplanitField;
            }
            set {
                this.tipiAeroplanitField = value;
                this.RaisePropertyChanged("TipiAeroplanit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public MarkaAeroplanit MarkaAeroplanit {
            get {
                return this.markaAeroplanitField;
            }
            set {
                this.markaAeroplanitField = value;
                this.RaisePropertyChanged("MarkaAeroplanit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int NumriUleseve {
            get {
                return this.numriUleseveField;
            }
            set {
                this.numriUleseveField = value;
                this.RaisePropertyChanged("NumriUleseve");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fidanabdiu.netfirms.com/")]
    public partial class LinjaAjrore : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string emriField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Emri {
            get {
                return this.emriField;
            }
            set {
                this.emriField = value;
                this.RaisePropertyChanged("Emri");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fidanabdiu.netfirms.com/")]
    public partial class TipiAeroplanit : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string emriField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Emri {
            get {
                return this.emriField;
            }
            set {
                this.emriField = value;
                this.RaisePropertyChanged("Emri");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fidanabdiu.netfirms.com/")]
    public partial class MarkaAeroplanit : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string emriField;
        
        private TipiAeroplanit tipiAeroplanitField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Emri {
            get {
                return this.emriField;
            }
            set {
                this.emriField = value;
                this.RaisePropertyChanged("Emri");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public TipiAeroplanit TipiAeroplanit {
            get {
                return this.tipiAeroplanitField;
            }
            set {
                this.tipiAeroplanitField = value;
                this.RaisePropertyChanged("TipiAeroplanit");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fidanabdiu.netfirms.com/")]
    public enum UlesjaEZene {
        
        /// <remarks/>
        JO,
        
        /// <remarks/>
        PO,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fidanabdiu.netfirms.com/")]
    public partial class Rezervimi : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private PerdoruesiAgjensionit perdoruesiAgjensionitField;
        
        private Fluturimi fluturimiField;
        
        private Udhetari udhetariField;
        
        private Ulesja ulesjaField;
        
        private LlojiIRezervimit llojiRezervimitField;
        
        private decimal cmimiField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public PerdoruesiAgjensionit PerdoruesiAgjensionit {
            get {
                return this.perdoruesiAgjensionitField;
            }
            set {
                this.perdoruesiAgjensionitField = value;
                this.RaisePropertyChanged("PerdoruesiAgjensionit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public Fluturimi Fluturimi {
            get {
                return this.fluturimiField;
            }
            set {
                this.fluturimiField = value;
                this.RaisePropertyChanged("Fluturimi");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public Udhetari Udhetari {
            get {
                return this.udhetariField;
            }
            set {
                this.udhetariField = value;
                this.RaisePropertyChanged("Udhetari");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public Ulesja Ulesja {
            get {
                return this.ulesjaField;
            }
            set {
                this.ulesjaField = value;
                this.RaisePropertyChanged("Ulesja");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public LlojiIRezervimit LlojiRezervimit {
            get {
                return this.llojiRezervimitField;
            }
            set {
                this.llojiRezervimitField = value;
                this.RaisePropertyChanged("LlojiRezervimit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public decimal Cmimi {
            get {
                return this.cmimiField;
            }
            set {
                this.cmimiField = value;
                this.RaisePropertyChanged("Cmimi");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fidanabdiu.netfirms.com/")]
    public partial class Fluturimi : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private Aeroplani aeroplaniField;
        
        private Qyteti qytetiField;
        
        private System.DateTime dataNisjesField;
        
        private System.DateTime oraNisjesField;
        
        private PerdoruesiAeroportit perdoruesiAeroportitField;
        
        private FluturimiAnuluar fluturimiAnuluarField;
        
        private decimal cmimiField;
        
        private decimal cmimiKthyesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Aeroplani Aeroplani {
            get {
                return this.aeroplaniField;
            }
            set {
                this.aeroplaniField = value;
                this.RaisePropertyChanged("Aeroplani");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public Qyteti Qyteti {
            get {
                return this.qytetiField;
            }
            set {
                this.qytetiField = value;
                this.RaisePropertyChanged("Qyteti");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime DataNisjes {
            get {
                return this.dataNisjesField;
            }
            set {
                this.dataNisjesField = value;
                this.RaisePropertyChanged("DataNisjes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public System.DateTime OraNisjes {
            get {
                return this.oraNisjesField;
            }
            set {
                this.oraNisjesField = value;
                this.RaisePropertyChanged("OraNisjes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public PerdoruesiAeroportit PerdoruesiAeroportit {
            get {
                return this.perdoruesiAeroportitField;
            }
            set {
                this.perdoruesiAeroportitField = value;
                this.RaisePropertyChanged("PerdoruesiAeroportit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public FluturimiAnuluar FluturimiAnuluar {
            get {
                return this.fluturimiAnuluarField;
            }
            set {
                this.fluturimiAnuluarField = value;
                this.RaisePropertyChanged("FluturimiAnuluar");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public decimal Cmimi {
            get {
                return this.cmimiField;
            }
            set {
                this.cmimiField = value;
                this.RaisePropertyChanged("Cmimi");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public decimal CmimiKthyes {
            get {
                return this.cmimiKthyesField;
            }
            set {
                this.cmimiKthyesField = value;
                this.RaisePropertyChanged("CmimiKthyes");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fidanabdiu.netfirms.com/")]
    public partial class Qyteti : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string emriField;
        
        private Shteti shtetiField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Emri {
            get {
                return this.emriField;
            }
            set {
                this.emriField = value;
                this.RaisePropertyChanged("Emri");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public Shteti Shteti {
            get {
                return this.shtetiField;
            }
            set {
                this.shtetiField = value;
                this.RaisePropertyChanged("Shteti");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fidanabdiu.netfirms.com/")]
    public partial class Shteti : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string emriField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Emri {
            get {
                return this.emriField;
            }
            set {
                this.emriField = value;
                this.RaisePropertyChanged("Emri");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fidanabdiu.netfirms.com/")]
    public partial class PerdoruesiAeroportit : Personi {
        
        private string pseudonimiField;
        
        private string fjalekalimiField;
        
        private Privilegji privilegjiField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Pseudonimi {
            get {
                return this.pseudonimiField;
            }
            set {
                this.pseudonimiField = value;
                this.RaisePropertyChanged("Pseudonimi");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Fjalekalimi {
            get {
                return this.fjalekalimiField;
            }
            set {
                this.fjalekalimiField = value;
                this.RaisePropertyChanged("Fjalekalimi");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public Privilegji Privilegji {
            get {
                return this.privilegjiField;
            }
            set {
                this.privilegjiField = value;
                this.RaisePropertyChanged("Privilegji");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fidanabdiu.netfirms.com/")]
    public enum Privilegji {
        
        /// <remarks/>
        Administrator,
        
        /// <remarks/>
        Punetor,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Udhetari))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PerdoruesiAeroportit))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PerdoruesiAgjensionit))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fidanabdiu.netfirms.com/")]
    public abstract partial class Personi : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string emriField;
        
        private string mbiemriField;
        
        private string numriIdentifikuesField;
        
        private DokumentiIdentifikues dokumentiIdentifikuesField;
        
        private System.DateTime datelindjaField;
        
        private string vendlindjaField;
        
        private string vendbanimiField;
        
        private string adresaField;
        
        private string telefoniFiksField;
        
        private string telefoniMobilField;
        
        private string emailiField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Emri {
            get {
                return this.emriField;
            }
            set {
                this.emriField = value;
                this.RaisePropertyChanged("Emri");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Mbiemri {
            get {
                return this.mbiemriField;
            }
            set {
                this.mbiemriField = value;
                this.RaisePropertyChanged("Mbiemri");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string NumriIdentifikues {
            get {
                return this.numriIdentifikuesField;
            }
            set {
                this.numriIdentifikuesField = value;
                this.RaisePropertyChanged("NumriIdentifikues");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public DokumentiIdentifikues DokumentiIdentifikues {
            get {
                return this.dokumentiIdentifikuesField;
            }
            set {
                this.dokumentiIdentifikuesField = value;
                this.RaisePropertyChanged("DokumentiIdentifikues");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public System.DateTime Datelindja {
            get {
                return this.datelindjaField;
            }
            set {
                this.datelindjaField = value;
                this.RaisePropertyChanged("Datelindja");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Vendlindja {
            get {
                return this.vendlindjaField;
            }
            set {
                this.vendlindjaField = value;
                this.RaisePropertyChanged("Vendlindja");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Vendbanimi {
            get {
                return this.vendbanimiField;
            }
            set {
                this.vendbanimiField = value;
                this.RaisePropertyChanged("Vendbanimi");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Adresa {
            get {
                return this.adresaField;
            }
            set {
                this.adresaField = value;
                this.RaisePropertyChanged("Adresa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string TelefoniFiks {
            get {
                return this.telefoniFiksField;
            }
            set {
                this.telefoniFiksField = value;
                this.RaisePropertyChanged("TelefoniFiks");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string TelefoniMobil {
            get {
                return this.telefoniMobilField;
            }
            set {
                this.telefoniMobilField = value;
                this.RaisePropertyChanged("TelefoniMobil");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string Emaili {
            get {
                return this.emailiField;
            }
            set {
                this.emailiField = value;
                this.RaisePropertyChanged("Emaili");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fidanabdiu.netfirms.com/")]
    public enum DokumentiIdentifikues {
        
        /// <remarks/>
        Leternjoftim,
        
        /// <remarks/>
        Patente,
        
        /// <remarks/>
        Pasaporte,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fidanabdiu.netfirms.com/")]
    public partial class Udhetari : Personi {
        
        private PerdoruesiAgjensionit perdoruesiAgjensionitField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public PerdoruesiAgjensionit PerdoruesiAgjensionit {
            get {
                return this.perdoruesiAgjensionitField;
            }
            set {
                this.perdoruesiAgjensionitField = value;
                this.RaisePropertyChanged("PerdoruesiAgjensionit");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fidanabdiu.netfirms.com/")]
    public enum FluturimiAnuluar {
        
        /// <remarks/>
        JO,
        
        /// <remarks/>
        PO,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fidanabdiu.netfirms.com/")]
    public enum LlojiIRezervimit {
        
        /// <remarks/>
        NjeKahesh,
        
        /// <remarks/>
        Kthyes,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface WSSoapChannel : AgjensioniTuristik.Serveri.WSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class WSSoapClient : System.ServiceModel.ClientBase<AgjensioniTuristik.Serveri.WSSoap>, AgjensioniTuristik.Serveri.WSSoap {
        
        public WSSoapClient() {
        }
        
        public WSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public AgjensioniTuristik.Serveri.PerdoruesiAgjensionit Kycu(string pseudonimi, string fjalekalimi) {
            return base.Channel.Kycu(pseudonimi, fjalekalimi);
        }
        
        public AgjensioniTuristik.Serveri.PerdoruesiAgjensionit PerdoruesiAgjensionitShkruaj(AgjensioniTuristik.Serveri.PerdoruesiAgjensionit pa) {
            return base.Channel.PerdoruesiAgjensionitShkruaj(pa);
        }
        
        public AgjensioniTuristik.Serveri.PerdoruesiAgjensionit PerdoruesiAgjensionitNdrysho(AgjensioniTuristik.Serveri.PerdoruesiAgjensionit pa) {
            return base.Channel.PerdoruesiAgjensionitNdrysho(pa);
        }
        
        public AgjensioniTuristik.Serveri.PerdoruesiAgjensionit PerdoruesiAgjensionitLexo(int ID) {
            return base.Channel.PerdoruesiAgjensionitLexo(ID);
        }
        
        public void PerdoruesiAgjensionitFshi(AgjensioniTuristik.Serveri.PerdoruesiAgjensionit pa) {
            base.Channel.PerdoruesiAgjensionitFshi(pa);
        }
        
        public PerdoruesiAgjensionit[] PerdoruesiAgjensionitLexoSipasAgjensionit(int AgjensioniID) {
            return base.Channel.PerdoruesiAgjensionitLexoSipasAgjensionit(AgjensioniID);
        }
        
        public Fluturimi[] FluturimetLexo(string fjalakyce) {
            return base.Channel.FluturimetLexo(fjalakyce);
        }
        
        public AgjensioniTuristik.Serveri.Rezervimi RezervimiShkruaj(AgjensioniTuristik.Serveri.Rezervimi r) {
            return base.Channel.RezervimiShkruaj(r);
        }
        
        public AgjensioniTuristik.Serveri.Rezervimi RezervimiNdrysho(AgjensioniTuristik.Serveri.Rezervimi r) {
            return base.Channel.RezervimiNdrysho(r);
        }
        
        public AgjensioniTuristik.Serveri.Rezervimi RezervimiLexo(int ID) {
            return base.Channel.RezervimiLexo(ID);
        }
        
        public void RezervimiFshi(AgjensioniTuristik.Serveri.Rezervimi r) {
            base.Channel.RezervimiFshi(r);
        }
        
        public Rezervimi[] RezervimetLexoSipasAgjensionit(int AgjensioniID) {
            return base.Channel.RezervimetLexoSipasAgjensionit(AgjensioniID);
        }
        
        public AgjensioniTuristik.Serveri.Udhetari UdhetariShkruaj(AgjensioniTuristik.Serveri.Udhetari u) {
            return base.Channel.UdhetariShkruaj(u);
        }
        
        public AgjensioniTuristik.Serveri.Udhetari UdhetariNdrysho(AgjensioniTuristik.Serveri.Udhetari u) {
            return base.Channel.UdhetariNdrysho(u);
        }
        
        public AgjensioniTuristik.Serveri.Udhetari UdhetariLexo(int ID) {
            return base.Channel.UdhetariLexo(ID);
        }
        
        public Udhetari[] UdhetaretLexo(string fjalakyce) {
            return base.Channel.UdhetaretLexo(fjalakyce);
        }
        
        public Ulesja[] UlesetLexoSipasAeroplanit(int AeroplaniID) {
            return base.Channel.UlesetLexoSipasAeroplanit(AeroplaniID);
        }
        
        public void UdhetariFshi(AgjensioniTuristik.Serveri.Udhetari u) {
            base.Channel.UdhetariFshi(u);
        }
        
        public AgjensioniTuristik.Serveri.Ulesja UlesjaNdrysho(AgjensioniTuristik.Serveri.Ulesja u) {
            return base.Channel.UlesjaNdrysho(u);
        }
        
        public Ulesja[] UlesetLexoSipasStatusit(int AeroplaniID, AgjensioniTuristik.Serveri.UlesjaEZene UlesjaEZene) {
            return base.Channel.UlesetLexoSipasStatusit(AeroplaniID, UlesjaEZene);
        }
        
        public Fluturimi[] FluturimetLexoSipasStatusit(AgjensioniTuristik.Serveri.FluturimiAnuluar FluturimiAnuluar) {
            return base.Channel.FluturimetLexoSipasStatusit(FluturimiAnuluar);
        }
        
        public bool LexoUlesetLira(int AeroplaniID, AgjensioniTuristik.Serveri.UlesjaEZene UlesjaEZene) {
            return base.Channel.LexoUlesetLira(AeroplaniID, UlesjaEZene);
        }
    }
}
